apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - backend
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: backend
          image: shinjimc/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:VMBoSXotYMaVvFSsYxDyulEAVmArGrlM@hopper.proxy.rlwy.net:53449/test?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 32000
